import React from 'react'


export const metadata = {
  title: "About us",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
        About
    </div>
  )
}
