import './globals.css';
import 'aos/dist/aos.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import 'react-toastify/dist/ReactToastify.min.css';
import { NavigationbarWithDropdownMultilevelMenu } from '@/components/shared/Navbar';
import FooterGlobal from '@/components/shared/FooterGlobal';

export const metadata = {
    title: 'Home | Webbriks',
    description: 'Generated by create next app',
};

export default function MyFunc({ children }) {
    return (
        <html lang="en" data-theme="light">
            <head>
                <link
                    rel="icon"
                    type="image/png"
                    href="https://iili.io/dj5tSSf.png"
                />
            </head>

            <body className="bg-[#FFFBF4]">
                <header className="lg:sticky lg:-top-2 z-50 shadow-sm">
                    <NavigationbarWithDropdownMultilevelMenu />
                </header>
                <main className="z-0">{children}</main>
                <footer>
                    <FooterGlobal />
                </footer>
            </body>
        </html>
    );
}
