import Header from "@/components/Header";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Header />
        </header>

        <main>{children}</main>

        <h2>Footer</h2>
      </body>
    </html>
  );
}
