import RootServicesPage from '@/components/services/RootServicesPage';

export const metadata = {
    title: 'Services | Webbriks',
    description: 'Generated by create next app',
};

export default async function ServicePage() {
    return <RootServicesPage />;
}

